#ifndef POINTCLOUDVIEWER_WORKERS_OFFLINERENDERER_DIALOG_HPP_
#define POINTCLOUDVIEWER_WORKERS_OFFLINERENDERER_DIALOG_HPP_

#include <pointcloud_viewer/workers/offline_renderer.hpp>

#include <QPair>

class MainWindow;


#endif // POINTCLOUDVIEWER_WORKERS_OFFLINERENDERER_DIALOG_HPP_
